### ISSUE TITLE
[속보] 최경민? 그는 이주원과 말을 놓은 사실이....!

### ISSUE THREAD

**Issue by jang010505** [KimWash/KimWash#1]
헉
 인천대학교 컴퓨터공학부 2학년 2021.03 ~
?? 21학번 어쩐지 주원이랑 말 까더니 ㄹㅇㅋㅋ

**Comment by KimWash** [comment]
> 헉
> 
>  인천대학교 컴퓨터공학부 2학년 2021.03 ~
> 
> ?? 21학번 어쩐지 주원이랑 말 까더니 ㄹㅇㅋㅋ

어머 죄송합니다 수정하겠습니다
